### ISSUE TITLE
Coordinate with iOS group to make app iOS-friendly (FSND/iOSND)

### ISSUE THREAD

**Issue by allanbreyes** [mudacity/udyssey#8]
@mudacity/ios-devs - would like some input here on what's needed to have an iOS app talk with the Flask app.  No clue :stuck_out_tongue:

**Comment by ccrazy88** [comment]
If the iOS app is going to use the Google Maps SDK, then it should be pretty easy—we'll just need the same encoded path that the web app will probably use to display something.

If we're going to use the standard maps display, we'd ideally want each waypoint's latitude/longitude coordinates because Google Maps' geocoding might differ from Apple's geocoding. However, storing Google Maps' geocoding results and using them on Apple's maps is against TOS, so we'd probably just have to deal with a list of addresses and hope for the best.

**Comment by allanbreyes** [comment]
Interesting... I think then that it makes sense to use lat/lon.  I was thinking it might make sense to issue a POST request w/ a JSON of locations (issue #4) and then the API would return a list of ordered waypoints (the optimized road trip route).  Would this be compatible?  I'm trying to wrap my head around what work should be done on the back-end vs. front-end.  Makes sense to load as much on the back-end, so there's no functionality duplication between the iOS app and the web front-end (KnockoutJS).  Thoughts, anyone?

**Comment by ccrazy88** [comment]
Yes, that would be fine. The iOS app would be relatively simple in that case, but that's perfectly fine with me, I think. This project in general seems to me like it should be more backend-heavy anyway.
